name: timesheet
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl: ^0.18.1
  camera: ^0.10.0+4
  path: ^1.8.2
  get: ^4.6.5
  flutter_local_notifications: ^12.0.2
  path_provider: ^2.0.11
  url_strategy: ^0.2.0
  pin_code_fields: ^7.4.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.4.0+3
  flutter_typeahead: ^4.1.1
  carousel_slider: ^4.1.1
  shimmer_animation: ^2.1.0+1
  image_picker: ^0.8.6
  universal_html: ^2.0.8
  universal_platform: ^1.0.0+1
  flutter_inappwebview: ^5.6.0+1
  flutter_widget_from_html: ^0.8.5
  fwfh_selectable_text: ^0.8.3+1
  flutter_html: ^3.0.0-alpha.6
  url_launcher: ^6.1.6
  http: ^0.13.5
  pointer_interceptor: ^0.9.3+3
  phone_number: ^1.0.0
  cached_network_image: ^3.2.2
  photo_view: ^0.14.0
  dotted_border: ^2.0.0+2
  share_plus: ^6.0.1
  flutter_launcher_icons: ^0.11.0
  shared_preferences: ^2.0.15
  fancy_snackbar:
    git:
      url: https://github.com/MR0100/fancy_snackbar.git
  json_annotation: ^4.8.1
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.5
  flutter_contacts: ^1.1.5+1
  azlistview: ^2.0.0
  modal_bottom_sheet: ^2.1.2
  slide_to_confirm: ^1.1.0
  lottie: ^2.0.0
  expandable_bottom_sheet: ^1.1.1+1
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^3.0.4
  flutter_svg: ^1.1.5
  shimmer: ^2.0.0
  permission_handler: ^10.1.0
  screenshot: ^1.2.3
  gallery_saver: ^2.3.2
  modal_progress_hud_nsn: ^0.3.0
  path_drawing: ^1.0.1
  currency_text_input_formatter: ^2.1.7
  flutter_custom_tabs: ^1.0.4
  local_auth: ^2.1.2
  #  google_mlkit_barcode_scanning: ^0.5.0
  #  google_mlkit_face_detection: ^0.5.0x
  flutter_secure_storage: ^6.0.0
  app_settings: ^4.1.8
  percent_indicator: ^4.2.2
  #  firebase_app_check: ^0.1.1+2
  flutter_native_splash: ^2.2.13
  flutter_countdown_timer: ^4.1.0
  qr_flutter: ^4.0.0
  crypto: ^3.0.2
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0
  firebase_crashlytics: ^3.0.2
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"
flutter_native_splash:
  color: "#ffffff"
  image: assets/image/logo.png
  android_12:
    image: assets/image/logo.png
    icon_background_color: "#ffffff"
  android: true
  ios: true
flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/animationFile/

  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/font/LatoRegular.ttf
          weight: 400
        - asset: assets/font/LatoMedium.ttf
          weight: 500
        - asset: assets/font/LatoBold.ttf
          weight: 700
        - asset: assets/font/Lato_Semibold.ttf
          weight: 900
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Medium.ttf
        - asset: assets/font/Inter-Black.ttf
          weight: 900
        - asset: assets/font/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Inter-SemiBold.ttf
          weight: 700
        - asset: assets/font/Inter-Bold.ttf
          weight: 600
        - asset: assets/font/Inter-Regular.ttf
          weight: 400
        - asset: assets/font/Inter-Light.ttf
          weight: 300
        - asset: assets/font/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Inter-Thin.ttf
          weight: 100


