// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGz7nBNkuU0h5UjcwynH2jlOEflvgDBjo',
    appId: '1:50599405772:web:1d8b2b5b1632b0a4793a69',
    messagingSenderId: '50599405772',
    projectId: 'timesheet-oct',
    authDomain: 'timesheet-oct.firebaseapp.com',
    databaseURL: 'https://timesheet-oct-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timesheet-oct.appspot.com',
    measurementId: 'G-2J38SCGLE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4woZqSHUKuHdKrQo72hWBObfxbugiZno',
    appId: '1:50599405772:android:4e525f08727bff14793a69',
    messagingSenderId: '50599405772',
    projectId: 'timesheet-oct',
    databaseURL: 'https://timesheet-oct-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timesheet-oct.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO33CbpkP528dRrp_lW35lWbx5ztcbMvo',
    appId: '1:50599405772:ios:ec2088d6294f018f793a69',
    messagingSenderId: '50599405772',
    projectId: 'timesheet-oct',
    databaseURL: 'https://timesheet-oct-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timesheet-oct.appspot.com',
    androidClientId: '50599405772-hf992ei15e3cdt0b7jss2vgpflamn7n3.apps.googleusercontent.com',
    iosClientId: '50599405772-061i598vdh9gnbm6asro2qpdggvto91v.apps.googleusercontent.com',
    iosBundleId: 'com.example.timesheet',
  );
}
